module.exports = {
    // HOST: 'localhost',
    // USER: 'root',
    // PASSWORD: 'bakalaurasdb',
    // DB: 'PhotoSite',
    // dialect: 'mysql',
    // pool: {
    //     max: 5,
    //     min: 0,
    //     acquire: 30000,
    //     idle: 10000,
    // },
    HOST: '193.219.91.103',
    PORT: 12982,
    USER: 'paka5521',
    PASSWORD: 'PhotoSiteDB',
    DB: 'PhotoSite',
    dialect: 'mysql',
    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000,
    },
}
